# Generated by Django 4.2.2 on 2024-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(max_length=200, null=True, verbose_name="Компания"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=50, unique=True, verbose_name="Email"),
        ),
    ]
