# Generated by Django 4.2.2 on 2024-05-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_company_remove_user_company_user_user_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_user_list", "Может просматривать список пользователей"),
                    ("can_block_users", "Может блокировать пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
