# Generated by Django 4.2.2 on 2024-05-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "cannot_view_user_list",
                        "Не может просматривать список пользователей",
                    ),
                    (
                        "cannot_change_user_list",
                        "Не может изменять список пользователей",
                    ),
                    (
                        "cannot_delete_user_list",
                        "Не может удалять список пользователей",
                    ),
                    ("cannot_add_user", "Не может добавлять пользователя"),
                    ("cannot_change_user", "Не может изменять пользователя"),
                    ("cannot_delete_user", "Не может удалять пользователя"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
