# Generated by Django 4.2.2 on 2024-05-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_company_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("cannot_block_user", "Не может блокировать пользователя"),
                    ("can_change_newsletter", "Может изменять рассылки"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
