# Generated by Django 4.2.2 on 2024-05-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "cannot_view_users_list",
                        "Не может просматривать список пользователей",
                    ),
                    ("cannot_block_user", "Может блокировать пользователя"),
                    ("can_view_newsletter", "Может просматривать рассылки"),
                    ("cannot_disable_newsletter", "Не может отключать рассылки"),
                    ("can_change_newsletter", "Может редактировать рассылки"),
                    ("can_delete_newsletter", "Может удалять рассылки"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
