# Generated by Django 4.2.2 on 2024-05-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block", "Можно заблокировать"),
                    ("can_view_users", "Можно просматривать пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
