# Generated by Django 4.2.2 on 2024-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='message',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.ManyToManyField(to='schedule.textfornewsletter', verbose_name='Сообщение для отправки'),
        ),
    ]
