# Generated by Django 4.2.2 on 2024-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_newsletter_message_newsletter_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(help_text='Введите свой email', max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
