# Generated by Django 4.2.2 on 2024-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_log_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='clients_list',
        ),
        migrations.RemoveField(
            model_name='log',
            name='mailing_list',
        ),
        migrations.AlterField(
            model_name='log',
            name='server_response',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AddField(
            model_name='log',
            name='clients_list',
            field=models.ManyToManyField(blank=True, null=True, to='schedule.client', verbose_name='Клиенты для рассылки'),
        ),
        migrations.AddField(
            model_name='log',
            name='mailing_list',
            field=models.ManyToManyField(blank=True, null=True, to='schedule.newsletter', verbose_name='Письма для рассылки'),
        ),
    ]
