# Generated by Django 4.2.2 on 2024-05-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_client_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('раз в день', 'Ежедневно'), ('раз в неделю', 'Еженедельно'), ('раз в месяц', 'Ежемесячно')], max_length=300, verbose_name='Частота отправки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status_of_newsletter',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Отправлено', 'Запущена'), ('Завершена', 'Завершена')], max_length=150, verbose_name='статус рассылки'),
        ),
    ]
