# Generated by Django 4.2.2 on 2024-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_newsletter_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfornewsletter',
            name='clients',
            field=models.ManyToManyField(blank=True, to='schedule.client', verbose_name='Клиенты для рассылки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='clients_list',
            field=models.ManyToManyField(blank=True, to='schedule.client', verbose_name='Клиенты для рассылки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='mailing_list',
            field=models.ManyToManyField(blank=True, to='schedule.newsletter', verbose_name='Письма для рассылки'),
        ),
    ]
