# Generated by Django 4.2.2 on 2024-05-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_textfornewsletter_clients_alter_log_clients_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Лог отправки сообщения', 'verbose_name_plural': 'Логи отправки сообщений'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='clients_list',
        ),
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.textfornewsletter', verbose_name='Сообщение'),
        ),
        migrations.RemoveField(
            model_name='log',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='log',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.newsletter', verbose_name='Рассылка'),
        ),
    ]
