# Generated by Django 4.2.2 on 2024-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_alter_newsletter_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
