# Generated by Django 4.2.2 on 2024-05-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_alter_newsletter_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_view_newsletter", "Может видеть все рассылки"),
                    ("can_disable_newsletter", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="textfornewsletter",
            options={
                "permissions": [
                    (
                        "cann_change_textfornewsletter_list",
                        "Может изменять текст для рассылок",
                    )
                ],
                "verbose_name": "Текст для отправки",
                "verbose_name_plural": "Тексты для рассылок",
            },
        ),
    ]
