# Generated by Django 4.2.2 on 2024-05-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_change_newsletter_list", "Может изменять рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
