# Generated by Django 4.2.2 on 2024-05-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0014_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_view_newsletter", "Может просматривать рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
