# Generated by Django 4.2.2 on 2024-05-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0016_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_view_newsletter", "Может видеть все рассылки"),
                    ("can_disable_newsletter", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
