# Generated by Django 4.2.2 on 2024-05-30 20:39

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0018_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_view_all_newsletter", "Может видеть все рассылки"),
                    ("can_disable_newsletter", "Может отключать рассылки"),
                    ("cannot_change_newsletter", "Не может изменять рассылки"),
                    ("cannot_delete_newsletter", "Не может удалять рассылки"),
                    ("cannot_create_newsletter", "Не может создавать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
