# Generated by Django 4.2.2 on 2024-06-03 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0019_alter_newsletter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status_of_newsletter",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("В работе", "Запущена"),
                    ("Завершена", "Завершена"),
                    ("Ошибка отправки", "Ошибка отправки"),
                ],
                max_length=150,
                verbose_name="статус рассылки",
            ),
        ),
    ]
